import { 
  PenSquare, History, BarChart3, Clock, CheckCircle, UserCheck,
  Users, LayoutDashboard, Tags, Sliders, FileBarChart
} from "lucide-react";

export const DASHBOARD_CARDS = [
  {
    id: "apply-leave",
    title: "Apply for Leave",
    description: "Submit leave applications easily with a guided form — select dates, choose acting members and send your request in minutes",
    icon: PenSquare,
    iconColor: "#1E88E5", 
    path: "/apply",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
      "Standard Member",
    ],
  },
  {
    id: "my-history",
    title: "My Leave History",
    description: "Track previously approved leave applications and monitor remaining carry-over days for each leave type",
    icon: History,
    iconColor: "#8E24AA", 
    path: "/my-leave-history",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
      "Standard Member",
    ],
  },
  {
    id: "my-reports",
    title: "View My Reports",
    description: "Monitor application status and get instant updates. Track pending, approved and rejected applications",
    icon: BarChart3,
    iconColor: "#43A047", 
    path: "/my-reports",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
      "Standard Member",
    ],
  },
  {
    id: "pending-requests",
    title: "Pending Leave Requests",
    description: "View and act on leave applications awaiting approval or rejection from acting and approving members",
    icon: Clock,
    iconColor: "#FB8C00", 
    path: "/pending-requests",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
      "Standard Member",
    ],
  },
  {
    id: "approve-reject",
    title: "Approve/Reject Leave",
    description: "Review detailed leave application submissions and make informed decisions by approving or rejecting requests",
    icon: CheckCircle,
    iconColor: "#43A047", 
    path: "/approve-reject-leaves",
    allowedRoles: ["Establishment Head"],
  },
  {
    id: "acting-confirmation",
    title: "Acting Member Confirmation",
    description: "Review and confirm leave requests where you are designated as the acting member during another user's absence.",
    icon: UserCheck,
    iconColor: "#FDD835", 
    path: "/acting-confirmation",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
      "Standard Member",
    ],
  },
  {
    id: "view-members",
    title: "View and Assign Establishment Members",
    description: "Manage all establishment users efficiently — create new users, edit profiles, assign ranks and define roles",
    icon: Users,
    iconColor: "#3949AB",
    path: "/users",
    allowedRoles: ["Super Administrator", "Establishment Administrator"],
  },
  {
    id: "leave-overview",
    title: "Leave Requests Overview",
    description: "Get a centralized overview of all establishment users' leave applications with their current approval statuses",
    icon: LayoutDashboard,
    iconColor: "#FB8C00", 
    path: "/leave-overview",
    allowedRoles: ["Super Administrator", "Establishment Administrator"],
  },
  {
    id: "leave-types",
    title: "Add/Edit Leave Types",
    description: "Manage and customize available leave categories to align with organizational leave structures",
    icon: Tags,
    iconColor: "#E91E63", 
    path: "/leave-types",
    allowedRoles: ["System Administrator"],
  },
  {
    id: "leave-criteria",
    title: "Configure Leave Criteria",
    description: "Define and adjust leave eligibility rules, limits and carry-over policies for each leave type",
    icon: Sliders,
    iconColor: "#8E24AA", 
    path: "/leave-criteria",
    allowedRoles: ["System Administrator"],
  },
  {
    id: "generate-reports",
    title: "Generate Reports",
    description: "Comprehensive reports summarizing leave data across personnel for record-keeping and analysis",
    icon: FileBarChart,
    iconColor: "#607D8B", 
    path: "/reports",
    allowedRoles: [
      "Super Administrator",
      "System Administrator",
      "Establishment Administrator",
      "Establishment Head",
    ],
  },
];
